#!/usr/bin/env bash
# Если вы это читаете, значит вы вышли за пределы игры
# и читаете код, который управляет игрой.
#
#                    Поздравляем!
#
# Изучение Linux — это прежде всего любопытство, так что
# читайте этот код и попробуйте понять, что он делает.
#
# Когда будете готовы продолжить игру, возвращайтесь
# к свиткам. Если застряли — создайте issue на Gitlab.
# Мы с радостью дадим подсказку.
#

ITEM=trinket

function askPutBackOnAltar() {
    echo "Хотите положить безделушку обратно на алтарь? y/n  "
    read RESP
    return $([ "$RESP" = "y" -o "$RESP" = "Y" ])
}

function askPutInInventory() {
    echo "Хотите забрать безделушку себе? y/n  "
    read RESP
    return $([ "$RESP" = "y" -o "$RESP" = "Y" ])
}

function askPutBackOnGround() {
    echo "Хотите положить безделушку обратно на пол?"
    echo "y/n  "
    read RESP
    return $([ "$RESP" = "y" -o "$RESP" = "Y" ])
}

function putOnAltar() {
    cat << EOF
Вы кладёте безделушку на алтарь. Вы чувствуете, как
лёгкий ветерок проносится по комнате.

EOF
    touch .bless
}

function putInInventory() {
    echo "Не забудьте добавить безделушку в инвентарь!"
    echo ""
    touch .curse
}

function leaveOnGround() {
    cat << EOF
Вы оставляете безделушку там, где она лежит. Здесь царит
великая печаль. Вы чувствуете, что нужно идти дальше.

EOF
    touch .curse
}

function remindRemoveInventory() {
    cat << EOF
Не забудьте убрать безделушку из инвентаря. Попробуйте
следующую команду:

export I=$(sed "s/$ITEM,//" <<< "$I")
EOF
}

echo "В углу стоит ветхий старый алтарь какого-то забытого бога."

if grep --quiet "$ITEM" <<< "$I" ; then
    if askPutBackOnAltar ; then
        putOnAltar
        remindRemoveInventory
        rm -f .curse
    elif askPutBackOnGround ; then
        leaveOnGround
        remindRemoveInventory
    else
        echo -e "Вы оставляете безделушку в инвентаре\n"
    fi
elif [ -f .bless ]; then
    if askPutInInventory ; then
        putInInventory
        rm .bless
    elif askPutBackOnGround ; then
        leaveOnGround
        rm .bless
    else
        echo -e "Вы оставляете безделушку на алтаре\n"
    fi
elif [ -f .curse ]; then
    if askPutBackOnAltar ; then
        putOnAltar
        rm .curse
    elif askPutInInventory ; then
        putInInventory
    else
        leaveOnGround
    fi
else
    cat << EOF
На полу лежит маленькая безделушка. Она выглядит
религиозной по своей природе.

EOF
    if askPutBackOnAltar ; then
        putOnAltar
    elif askPutInInventory ; then
        putInInventory
    else
        leaveOnGround
    fi
fi




































































































































































































































































































































































































































































































































































































# Хм, это не сработало.
# Помните, файлы со * — это программы.
# Попробуйте так:
#
# ./altar
#
# Если вы не видите * после
# имени этого файла, вероятно, вы
# забыли использовать ls -F



