#!/usr/bin/env bash

if [ $USER != "jovyan" ]; then
    echo Этот скрипт предназначен для настройки сессий mybinder.org
    echo Его не следует использовать в других целях
    exit 0
fi

cat >> ~/.bashrc << EOF
set +x +e
export PS1="bashcrawler\$ "
alias ls='ls --color=never'
cd entrance
cat ../.binder/welcome_message
EOF

exec "$@"
