#!/usr/bin/env bash
#
# Если вы это читаете, значит вы вышли за пределы игры
# и читаете код, который управляет игрой.
#
#                    Поздравляем!
#
# Изучение Linux — это прежде всего любопытство, так что
# читайте этот код и попробуйте понять, что он делает.
#
# Когда будете готовы продолжить игру, возвращайтесь
# к свиткам. Если застряли — создайте issue на Gitlab.
# Мы с радостью дадим подсказку.
#

#import global functions from toplevel directory
FUNCTIONS=$(pwd)
FUNCTIONS=${FUNCTIONS%entrance*}entrance/.functions
. $FUNCTIONS

roll() {
    printf "Введите число:  "
    read NUM
    ALPHA=$RANDOM
    OMEGA=$RANDOM
    A=`echo $ALPHA | cut -b 1-2`
    O=`echo $OMEGA | cut -b 1-2`
    let "NUM=$ALPHA % $OMEGA"
    MONSTER=$RANDOM
    MONSTER=`echo $MONSTER | cut -b 1-2`
    NUM=`echo $NUM | cut -b 1-2`

    echo "Монстр выбросил " $MONSTER
    echo "Вы выбросили " $NUM

    if [ -e ../../../.bless ]; then
	let "NUM=NUM+2"
	echo "+2 бонус от таинственного зимнего покровителя!"
    fi
}

resolve() {
    if [[ $MONSTER -eq $NUM ]]; then
        cat << EOF
Вы уклоняетесь от атаки, но промахиваетесь сами.
Бросайте снова...

EOF
	    roll
    fi

    if [[ $MONSTER -lt $NUM ]]; then
        cat << EOF
Попадание! Ощутимое попадание! Вы сразили дух
злого волшебника.

EOF
        cat << EOF > treasure
#!/usr/bin/env bash
if ! grep  --quiet --only-matching emerald <<< \$I; then
    cat << eof
Вы нашли *изумруд*! Добавьте его в инвентарь.

eof
else
    cat << eof
Это сокровище уже забрано.

eof
fi
EOF
       chmod +x treasure
       cat << EOF > platinum
#!/usr/bin/env bash
if ! grep  --quiet --only-matching platinum <<< \$I; then
    cat << eof
Вы нашли мешок *платиновых* монет! Добавьте его
в инвентарь.

eof
else
    cat << eof
Это сокровище уже забрано.

eof

fi
EOF
        chmod +x platinum
    else
        cat << EOF
Ваш меч рассекает воздух впустую. Вы получаете 5 единиц
урона. Вычтите это из переменной HP:

let HP=HP-5

EOF
        let HP=HP-5
        if [ "$HP" -le 0 ]; then
            cat << EOF
Вы внезапно чувствуете холод, жизненная сила покидает
ваше тело. Вы были убиты призраком злого волшебника.

КОНЕЦ ИГРЫ!

EOF
            gameover
            exit 1
        fi
	    roll
        resolve
    fi
}

cat << EOF
Комната сотрясается, порыв ветра обрушивается на вас
из ниоткуда. Вы чувствуете, что в комнату вошло некое
присутствие. Внезапная боль убеждает вас, что вы
атакованы призрачной сущностью!

Если у вас есть меч, вы можете атаковать. Иначе вам
лучше бежать.

EOF
printf "Хотите атаковать? y/n  "
read RESP

if [ "$RESP" = "y" -o "$RESP" = "Y" ];then
    roll
    resolve
else
    cat << EOF
Вы мудро разворачиваетесь и бежите. Скорее выполните cd
в предыдущую директорию.

EOF
fi



















































































































































































































































































# Хм, это не сработало.
# Помните, файлы со * — это программы.
# Попробуйте так:
#
# ./ghost


