#!/usr/bin/env bash
# Если вы это читаете, значит вы вышли за пределы игры
# и читаете код, который управляет игрой.
#
#                    Поздравляем!
#
# Изучение Linux — это прежде всего любопытство, так что
# читайте этот код и попробуйте понять, что он делает.
#
# Когда будете готовы продолжить игру, возвращайтесь
# к свиткам. Если застряли — создайте issue на Gitlab.
# Мы с радостью дадим подсказку.
#

#import global functions from toplevel directory
FUNCTIONS=$(pwd)
FUNCTIONS=${FUNCTIONS%entrance*}entrance/.functions
. $FUNCTIONS

roll() {
    printf "Введите число:  "
    read NUM
    ALPHA=$RANDOM
    OMEGA=$RANDOM
    A=`echo $ALPHA | cut -b 1-2`
    O=`echo $OMEGA | cut -b 1-2`
    let "NUM=$ALPHA % $OMEGA"
    MONSTER=$RANDOM
    MONSTER=`echo $MONSTER | cut -b 1-2`
    NUM=`echo $NUM | cut -b 1-2`
    echo "Монстр выбросил " $MONSTER
    echo "Вы выбросили " $NUM
    resolve
}

resolve() {
    if ! grep  --quiet --only-matching 'sword' <<< $I; then
        cat << EOF
У вас нет меча!

Ваши атаки будут менее эффективными.

EOF
        let NUM=NUM-10
    fi
    if [[ $MONSTER -eq $NUM ]]; then
        cat << EOF
Вы парируете атаки друг друга. Бросайте снова...

EOF
	roll
    fi

    if [[ $MONSTER -lt $NUM ]]; then
        cat << EOF
Попадание! Ощутимый удар! Вы сразили зверя.

EOF
        cat << EOF > treasure
#!/usr/bin/env bash
if ! grep  --quiet --only-matching crown <<< \$I; then
    cat << eof
Вы нашли **crown** (корону)! Добавьте её в инвентарь.

eof

else
    echo "Это сокровище уже забрано."
fi

EOF
        chmod +x treasure
        mv monster carcass
    else
        cat << EOF

Ваша атака отскакивает от кожистой плоти монстра.
Вы получаете 5 очков урона. Вычтите это из HP.

let HP=HP-5

EOF
        let HP=HP-5
        export HP
        if [ "$HP" -le 0 ]; then
            cat << EOF
Вы были убиты монстром.

КОНЕЦ ИГРЫ!

EOF
            gameover
            exit 1
        fi
	roll
    fi
}

if [ "$0" = "./carcass" ]; then
    cat << EOF
Вы находите тушу мерзкого зверя. В его останках нет
ничего интересного.

EOF
    exit 0
fi

cat << EOF
Громадный трёхногий зверь с пастью, полной клыков,
шипастым хвостом и 8 руками, надвигается на вас.

Если у вас есть меч, вы можете атаковать. Иначе лучше
бежать.

EOF
printf "Хотите атаковать? y/n  "
read RESP

if [ "$RESP" = "y" -o "$RESP" = "Y" ];then
    roll
else
    cat << EOF
Вы мудро разворачиваетесь и бежите. Скорее
перейдите в предыдущую директорию с помощью cd.

EOF
fi
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
##
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#

#
# Хм, это не сработало!
