#!/usr/bin/env bash
#
# Если вы это читаете, значит вы вышли за пределы игры
# и читаете код, который управляет игрой.
#
#                    Поздравляем!
#
# Изучение Linux — это прежде всего любопытство, так что
# читайте этот код и попробуйте понять, что он делает.
#
# Когда будете готовы продолжить игру, возвращайтесь
# к свиткам. Если застряли — создайте issue на Gitlab.
# Мы с радостью дадим подсказку.
#

#import global functions from toplevel directory
FUNCTIONS=$(pwd)
FUNCTIONS=${FUNCTIONS%entrance*}entrance/.functions
. $FUNCTIONS

roll() {
    echo "Введите число."
    read NUM
    ALPHA=$RANDOM
    OMEGA=$RANDOM
    A=`echo $ALPHA | cut -b 1-2`
    O=`echo $OMEGA | cut -b 1-2`
    let "NUM=$ALPHA % $OMEGA"
    MONSTER=$RANDOM
    MONSTER=`echo $MONSTER | cut -b 1-2`
    NUM=`echo $NUM | cut -b 1-2`

    let "MONSTER=MONSTER+3"

    if [ ! -e drum ]; then
       let "MONSTER=MONSTER-2"
    fi

    echo "Монстр выбросил " $MONSTER
    echo "Вы выбросили " $NUM

    if [[ -e wizard-dark && -e wizard-light ]]; then
	let "NUM=NUM+2"
	echo "+2 Арннисен Серый"
    fi

    if [[ -e ../../.bless ]]; then
	let "NUM=NUM+2"
	echo "+2 бонус волшебника POSIX!"
    fi
    resolve
}

flee () {
    cat << EOF
Вы пытаетесь бежать, но не можете. Вы проводите 1000 лет
безвольным слугой ползучего хаоса. Когда вы очнётесь,
вы сможете попытаться сразиться за своё освобождение.

EOF
}

resolve() {
    if [[ $MONSTER -eq $NUM ]]; then
        cat << EOF
Вы уклоняетесь от атаки, но промахиваетесь сами.
Бросайте снова...

EOF
	roll
    fi

    if [[ $MONSTER -lt $NUM ]]; then
        cat << EOF
Попадание! Ощутимое попадание! Вы одолели древнего бога
хаоса!

EOF
       cat << EOF > treasure
#!/usr/bin/env bash
if ! grep  --quiet --only-matching hair <<< \$I; then
    cat << eof
Вы нашли прядь **волос** бога! Добавьте её в инвентарь.

eof
else
    echo "Это сокровище уже забрано."
fi

EOF
       chmod +x treasure
       cat << EOF > platinum
#!/usr/bin/env bash
if ! grep  --quiet --only-matching bracelet <<< \$I; then
    cat << eof
Вы нашли зачарованный *браслет* хаотической
некромантии! Добавьте его в инвентарь.

eof
else
    echo "Это сокровище уже забрано."
fi

EOF
        chmod +x platinum
        cat << EOF > end
Вы достигли конца игры. Теперь вы знаете достаточно Bash,
чтобы использовать его в повседневных задачах. Практика
делает мастера, так что используйте его почаще. За новыми
советами по Bash заглядывайте на opensource.com.

А со временем мы надеемся увидеть, как вы добавите
собственные комнаты подземелья в Bashcrawl!

EOF

    else
        cat << EOF
Ваш меч рассекает воздух впустую. Вы получаете 10 единиц
урона от противника. Вычтите это из HP.

let "HP=HP-10"

EOF
        let HP=HP-10
        export HP
        if [ "$HP" -le 0 ]; then
            cat << EOF
Древний бог хаоса поглощает ваше тело и душу. Вы
были убиты.

КОНЕЦ ИГРЫ!

EOF
            gameover
            exit 1
        fi
	    roll
    fi
}

cat << EOF
В мгновение ока Ньярлатхотеп стоит перед вами.
Из его рук исходят чёрные некротические лучи,
и ваш разум кричит от боли.

EOF
printf "Вы вооружены? y/n  "
read RESP

if [ "$RESP" = "y" -o "$RESP" = "Y" ]; then

    if grep  --quiet --only-matching "sword" <<< $I; then
        roll
    else
        cat << EOF
О нет! Вы потеряли свой клинок! Ньярлатхотеп, древний
бог хаоса, чувствует вашу слабость.

EOF
        flee
    fi
else
    flee
fi



















































































































































































































































































# Хм, это не сработало.
#
# Помните, файлы со * — это программы.
# Попробуйте так:
#
# ./nyarlathotep
#
# Если вы не видите * после имени
# этого файла, вы, вероятно,
# забываете использовать ls -F


